spring.application.name=product-service
spring.config.import=optional:file:./.env[.properties]
spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}
